// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc5509.SwerveBotPly;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.phoenix.motorcontrol.can.WPI_TalonSRX;
import edu.wpi.first.wpilibj.Spark;
import edu.wpi.first.wpilibj.SpeedController;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static WPI_TalonSRX driveTrainFrontLeftTurn;
    public static WPI_TalonSRX driveTrainFrontRightTurn;
    public static WPI_TalonSRX driveTrainBackLeftTurn;
    public static WPI_TalonSRX driveTrainBackRightTurn;
    public static SpeedController driveTrainFrontLeftDrive;
    public static SpeedController driveTrainFrontRightDrive;
    public static SpeedController driveTrainBackLeftDrive;
    public static SpeedController driveTrainBackRightDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainFrontLeftTurn = new WPI_TalonSRX(2);
        
        
        driveTrainFrontRightTurn = new WPI_TalonSRX(3);
        
        
        driveTrainBackLeftTurn = new WPI_TalonSRX(4);
        
        
        driveTrainBackRightTurn = new WPI_TalonSRX(5);
        
        
        driveTrainFrontLeftDrive = new Spark(2);
        LiveWindow.addActuator("DriveTrain", "FrontLeftDrive", (Spark) driveTrainFrontLeftDrive);
        driveTrainFrontLeftDrive.setInverted(false);
        driveTrainFrontRightDrive = new Spark(3);
        LiveWindow.addActuator("DriveTrain", "FrontRightDrive", (Spark) driveTrainFrontRightDrive);
        driveTrainFrontRightDrive.setInverted(false);
        driveTrainBackLeftDrive = new Spark(4);
        LiveWindow.addActuator("DriveTrain", "BackLeftDrive", (Spark) driveTrainBackLeftDrive);
        driveTrainBackLeftDrive.setInverted(false);
        driveTrainBackRightDrive = new Spark(5);
        LiveWindow.addActuator("DriveTrain", "BackRightDrive", (Spark) driveTrainBackRightDrive);
        driveTrainBackRightDrive.setInverted(false);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
